AWSTemplateFormatVersion: '2010-09-09'
Description: Create DynamoDB tables "users" and "tasks" with on-demand capacity mode

Resources:
  UsersTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: users
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TasksTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: tasks
      AttributeDefinitions:
        - AttributeName: task_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: task_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: user_id-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL

Outputs:
  UsersTableArn:
    Description: ARN of the "users" DynamoDB table
    Value: !GetAtt UsersTable.Arn

  TasksTableArn:
    Description: ARN of the "tasks" DynamoDB table
    Value: !GetAtt TasksTable.Arn
